/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import controller.BLLKhachHang;
import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import object.KhachHang;

import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

import net.proteanit.sql.DbUtils;
/**
 *
 * @author Tran Huy Hoang
 */
public class TraPhong1 extends javax.swing.JFrame {

    /**
     * Creates new form TraPhong1
     */
    public TraPhong1() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
        }
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        DsTraPhong();
    }
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    public void DsTraPhong() {
        try {
            Con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QuanLyKhachSanV2;user=sa;password=huyhoang01");
            St = Con.createStatement();
            Rs = St.executeQuery("Select *from DanhSachDatPhong1");
            tbTraPhong.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void resetDuLieu() {
        txtMaDatPhong.setText("");
        txtMaKhachHang.setText("");
        txtTenKhachHang.setText("");
        txtCMND.setText("");
        txtTienPhong.setText("");
        txtSoPhong.setText("");
        txtSoNguoi.setText("");
        dateNgayThuePhong.setCalendar(null);
        dateNgayTraPhong.setCalendar(null);
        txtSoNgayO.setText("");
        txtBill.setText("");
        DsTraPhong();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaDatPhong = new javax.swing.JTextField();
        txtTienPhong = new javax.swing.JTextField();
        dateNgayThuePhong = new com.toedter.calendar.JDateChooser();
        txtMaKhachHang = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateNgayTraPhong = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSoPhong = new javax.swing.JTextField();
        txtSoNguoi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTraPhong = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txtSoNgayO = new javax.swing.JTextField();
        btnTraPhong = new javax.swing.JButton();
        btnInHoaDon = new javax.swing.JButton();
        btnXuatHoaDon = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTongDoanhThu = new javax.swing.JTextArea();
        btnXuatDoanhThu = new javax.swing.JButton();
        btnInDoanhThu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ TRẢ PHÒNG");

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Đặt Phòng:"));

        jLabel2.setText("Mã Đặt Phòng:");

        jLabel4.setText("Mã Khách Hàng:");

        jLabel5.setText("Tên Khách Hàng:");

        jLabel7.setText("Ngày Thuê Phòng:");

        jLabel8.setText("Tiền Phòng:");

        jLabel3.setText("CMND:");

        jLabel6.setText("Ngày Trả Phòng:");

        jLabel9.setText("Sô Phòng:");

        jLabel10.setText("Số Người:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtMaDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTenKhachHang)
                                .addComponent(txtMaKhachHang))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSoPhong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTienPhong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateNgayTraPhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(dateNgayThuePhong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCMND)
                            .addComponent(txtSoNguoi))))
                .addGap(91, 91, 91))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(dateNgayThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateNgayTraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSoPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSoNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tbTraPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Đặt Phòng", "Mã Khách Hàng", "Tên Khách Hàng", "CMND", "Ngày Đến", "Ngày Đi", "Tiền Thuê", "Số Phòng", "Số Người"
            }
        ));
        tbTraPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTraPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTraPhong);

        txtBill.setColumns(20);
        txtBill.setRows(5);
        jScrollPane2.setViewportView(txtBill);

        jLabel11.setText("Số Ngày Ở");

        btnTraPhong.setText("Trả Phòng");
        btnTraPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTraPhongMouseClicked(evt);
            }
        });

        btnInHoaDon.setText("In Hoá Đơn");
        btnInHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInHoaDonMouseClicked(evt);
            }
        });

        btnXuatHoaDon.setText("Xuất Hoá Đơn");
        btnXuatHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatHoaDonMouseClicked(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });

        txtTongDoanhThu.setColumns(20);
        txtTongDoanhThu.setRows(5);
        jScrollPane4.setViewportView(txtTongDoanhThu);

        btnXuatDoanhThu.setText("Xuất Doanh Thu");
        btnXuatDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatDoanhThuMouseClicked(evt);
            }
        });

        btnInDoanhThu.setText("In Doanh Thu");
        btnInDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInDoanhThuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addGap(286, 286, 286))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnTraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnXuatHoaDon)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoNgayO, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInDoanhThu)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnXuatDoanhThu)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(562, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(283, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSoNgayO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTraPhong)
                            .addComponent(btnThoat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXuatHoaDon)
                            .addComponent(btnInHoaDon))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXuatDoanhThu)
                            .addComponent(btnInDoanhThu))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(170, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(41, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );

        jPanel3.getAccessibleContext().setAccessibleName("Thông Tin Trả Phòng:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTraPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTraPhongMouseClicked
        // TODO add your handling code here:
        //SimpleDateFormat myFormat = new SimpleDateFormat("dd MM yyyy");
//String inputString1 = "23 01 1997";
//String inputString2 = "27 04 1997";
//myFormat.parse(inputString1)
//myFormat.parse(inputString2)
// Date date1 = dateNgayThuePhong.getDate();
//    Date date2 = ;


        DefaultTableModel model = (DefaultTableModel)tbTraPhong.getModel();
        int MyIndex = tbTraPhong.getSelectedRow();
        txtMaDatPhong.setText(model.getValueAt(MyIndex, 0).toString());
        txtMaKhachHang.setText(model.getValueAt(MyIndex, 1).toString());
        txtTenKhachHang.setText(model.getValueAt(MyIndex, 2).toString());
        txtCMND.setText(model.getValueAt(MyIndex, 3).toString());
        dateNgayThuePhong.setDate((java.util.Date) model.getValueAt(MyIndex, 4));
        dateNgayTraPhong.setDate((java.util.Date) model.getValueAt(MyIndex, 5));
        txtTienPhong.setText(model.getValueAt(MyIndex, 6).toString());
        txtSoPhong.setText(model.getValueAt(MyIndex, 7).toString());
        txtSoNguoi.setText(model.getValueAt(MyIndex, 8).toString());
        
         java.util.Date dateThue = dateNgayThuePhong.getDate();
    java.sql.Date sqlDateThue = new java.sql.Date(dateThue.getTime());
    java.util.Date dateTra = dateNgayTraPhong.getDate();
    java.sql.Date sqlDateTra = new java.sql.Date(dateTra.getTime());

   
    long diff = sqlDateTra.getTime() - sqlDateThue.getTime();
    long ngayo = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
        txtSoNgayO.setText(String.valueOf(ngayo));
    }//GEN-LAST:event_tbTraPhongMouseClicked

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatMouseClicked
    
    int  TienThuePhong = 0, TongDoanhThu=0;
    int i = 0;
    private void btnXuatHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatHoaDonMouseClicked
        // TODO add your handling code here:
        if(txtMaDatPhong.getText().isEmpty()||txtMaKhachHang.getText().isEmpty()
                ||txtTenKhachHang.getText().isEmpty()||txtCMND.getText().isEmpty()
                ||txtTienPhong.getText().isEmpty()||txtSoPhong.getText().isEmpty()||txtSoNguoi.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Chưa đủ thông tin !");
        }
        else {
            TienThuePhong = Integer.valueOf(txtTienPhong.getText()) * Integer.valueOf(txtSoNgayO.getText());
                txtBill.setText(txtBill.getText() + "\t==========Hoa Đon===========\n\n" 
                        + "MaDatPhong\tMaKhachHang\tTenKhachHang\tSoPhong\t\tNgayDen\t\t\t\tNgayDi\t\t\tTienThuePhong\n" + txtMaDatPhong.getText()
                        + "\t\t" + txtMaKhachHang.getText() + "\t\t" + txtTenKhachHang.getText() + "\t" + txtSoPhong.getText() + "\t" 
                        + dateNgayThuePhong.getDate()+ "\t" + dateNgayTraPhong.getDate()+ "\t" + TienThuePhong +"\n");
              
        }
    }//GEN-LAST:event_btnXuatHoaDonMouseClicked

    private void btnInHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInHoaDonMouseClicked
        try {
            // TODO add your handling code here:
            txtBill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(TraPhong1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInHoaDonMouseClicked

    private void btnTraPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTraPhongMouseClicked
        // TODO add your handling code here:
        if(txtMaDatPhong.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Chưa chọn phòng để trả !");
        else
            try{
                Con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QuanLyKhachSanV2;user=sa;password=huyhoang01");
                String MDP = txtMaDatPhong.getText();
                String Query = "Delete from DanhSachDatPhong1 where MaDatPhong = '"+MDP+"'";
                Statement Add = Con.createStatement();
                Add.executeUpdate(Query);
                DsTraPhong();
                JOptionPane.showMessageDialog(this, "Phòng đã được trả !");
                resetDuLieu();
            }catch (Exception e)
            {
                e.printStackTrace();
            }
    }//GEN-LAST:event_btnTraPhongMouseClicked

    private void btnInDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInDoanhThuMouseClicked
        try {
            // TODO add your handling code here:
            txtTongDoanhThu.print();
        } catch (PrinterException ex) {
            Logger.getLogger(TraPhong1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInDoanhThuMouseClicked

    private void btnXuatDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatDoanhThuMouseClicked
        // TODO add your handling code here:
         if(txtMaDatPhong.getText().isEmpty()||txtMaKhachHang.getText().isEmpty()
                ||txtTenKhachHang.getText().isEmpty()||txtCMND.getText().isEmpty()
                ||txtTienPhong.getText().isEmpty()||txtSoPhong.getText().isEmpty()||txtSoNguoi.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Chưa đủ thông tin !");
        }
        else {
         
         TienThuePhong = Integer.valueOf(txtTienPhong.getText()) * Integer.valueOf(txtSoNgayO.getText());
         TongDoanhThu = TongDoanhThu +TienThuePhong;
         i++;
               if (i == 1) {
               txtTongDoanhThu.setText(txtTongDoanhThu.getText() + "\t==========Doanh Thu===========\n\n" 
                        + "So\t\tMaDatPhong\tMaKhachHang\tTenKhachHang\tSoPhong\t\tNgayDen\t\t\t\tNgayDi\t\t\tTienThuePhong\t\tTongDoanhThu\n" + i + "\t\t" + txtMaDatPhong.getText()
                        + "\t\t" + txtMaKhachHang.getText() + "\t\t" + txtTenKhachHang.getText() + "\t" + txtSoPhong.getText() + "\t" 
                        + dateNgayThuePhong.getDate()+ "\t" + dateNgayTraPhong.getDate()+ "\t" + TienThuePhong+ "\t\t\t"+TongDoanhThu +"\n");
            } else {
                txtTongDoanhThu.setText(txtTongDoanhThu.getText() + i + "\t\t" + txtMaDatPhong.getText()
                        + "\t\t" + txtMaKhachHang.getText() + "\t\t" + txtTenKhachHang.getText() + "\t" + txtSoPhong.getText() + "\t" 
                        + dateNgayThuePhong.getDate()+ "\t" + dateNgayTraPhong.getDate()+ "\t" + TienThuePhong+ "\t\t\t"+TongDoanhThu +"\n");
            }
//               else{
//                    }
//            Grdtotallbl.setText("Tong Tien: " + GrdTotal);
        }
    }//GEN-LAST:event_btnXuatDoanhThuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraPhong1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraPhong1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraPhong1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraPhong1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraPhong1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInDoanhThu;
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTraPhong;
    private javax.swing.JButton btnXuatDoanhThu;
    private javax.swing.JButton btnXuatHoaDon;
    private com.toedter.calendar.JDateChooser dateNgayThuePhong;
    private com.toedter.calendar.JDateChooser dateNgayTraPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbTraPhong;
    private javax.swing.JTextArea txtBill;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtMaDatPhong;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtSoNgayO;
    private javax.swing.JTextField txtSoNguoi;
    private javax.swing.JTextField txtSoPhong;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTienPhong;
    private javax.swing.JTextArea txtTongDoanhThu;
    // End of variables declaration//GEN-END:variables
}
